cloudview/cloudview/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib.auth import views as auth_views
from django.conf.urls import include

from django.conf.urls.static import static
from django.conf import settings

from . import views

from user_authentication import views as user_auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('login', views.login, name='login_redirect'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('new-user/', user_auth_views.user_registration, name='user_registration'),
    path('', views.dashboard, name='dashboard'),
    path('catalog/', include('catalog.urls')),
    path('recognition/', include('recognition.urls')),
    path('report/', include('report.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cloudview/recognition/urls.py
from django.urls import path

from . import views

urlpatterns = [
	path('', views.person_list, name='person_list'),
	path('new-person', views.add_person, name='add_person'),
	path('new-person/<person_uuid>/contact', views.add_person_contact, name='add_person_contact'),
	path('new-person/<person_uuid>/images', views.add_person_images, name='add_person_images'),
	path('train/<person_uuid>', views.train_face, name='train_face'),
	path('delete-person/<person_uuid>', views.delete_person, name='delete_person'),
	path('select-source', views.analysis_index, name='analysis_index'),
	path('analysis/<source_type>', views.analysis_form, name='analysis_form'),
	path('manage-camera', views.manage_camera, name='manage_camera'),
	path('manage-video', views.manage_video, name='manage_video'),
	path('toggle-camera-status/<source_uuid>', views.toggle_camera_status, name='toggle_camera_status'),
	path('logs/<notification_type>/<related_uuid>', views.view_logs, name='view_logs'),
]

cloudview/report/urls.py
from django.urls import path

from . import views

urlpatterns = [
	path('', views.report, name='report'),
]

cloudview/recognition/models.py
from django.db import models
import uuid
from datetime import datetime

from django_countries.fields import CountryField

from catalog.models import Catalog
from user_authentication.models import User


def person_face_upload(instance, filename):
	filename = filename.split('/')
	filename = filename[len(filename)-1]
	return ('training-dataset/{}/{}/{}'.format(instance.person.user.uuid, instance.person.uuid, filename))


def video_file_upload(instance, filename):
	filename = filename.split('/')
	filename = filename[-1]
	return ('analysis-video/{}/{}'.format(instance.user.uuid, filename))


# Create your models here.
class Person(models.Model):
	GENDER_CHOICES = (
		('MALE', 'MALE'),
		('FEMALE', 'FEMALE'),
	)

	uuid = models.UUIDField(null=True, unique=True, default=uuid.uuid4, editable=False)
	first_name = models.CharField(max_length=100, null=True, blank=True)
	middle_name = models.CharField(max_length=100, null=True, blank=True)
	last_name = models.CharField(max_length=100, null=True, blank=True)
	gender = models.CharField(max_length=10, null=True, blank=True, choices=GENDER_CHOICES)
	email = models.EmailField(max_length=255, blank=True, null=True)
	phone_number = models.CharField(max_length=20, blank=True, null=True)
	street = models.CharField(max_length=100, blank=True, null=True)
	city = models.CharField(max_length=100, blank=True, null=True)
	state = models.CharField(max_length=100, blank=True, null=True)
	country = CountryField(blank=True, null=True, default='US')
	postal_code = models.IntegerField(blank=True, null=True)
	description = models.TextField(max_length=1000, blank=True, null=True)
	catalog = models.ForeignKey(Catalog, on_delete=models.CASCADE, blank=True, null=True)
	user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)

	def __str__(self):
		try:
			return str(self.catalog.catalog_name) + " - " + str(self.first_name)
		except:
			return "Undefined - " + str(self.first_name)


class PersonFace(models.Model):
	uuid = models.UUIDField(null=True, unique=True, default=uuid.uuid4, editable=False)
	image_name = models.ImageField(upload_to=person_face_upload, max_length=500)
	train_status = models.BooleanField(default=False)
	crop_face_image = models.CharField(max_length=500, blank=True, null=True)
	person = models.ForeignKey(Person, on_delete=models.CASCADE, blank=True, null=True)

	def __str__(self):
		return str(self.image_name)


class Notification(models.Model):
	NOTIFICATION_TYPE_CHOICES = (
		('train', 'TRAIN STATUS'),
		('analysis', 'ANALYSIS STATUS'),
		('source', 'SOURCE STATUS'),
	)
	uuid = models.UUIDField(null=True, unique=True, default=uuid.uuid4, editable=False)
	notification_type = models.CharField(max_length=100, choices=NOTIFICATION_TYPE_CHOICES)
	created_at = models.DateTimeField(auto_now_add=True)
	related_uuid = models.UUIDField(null=True, unique=False, editable=False)
	user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)


class NotificationHistory(models.Model):
	NOTIFICATION_STATUS_CHOICES = (
		('pending', 'PENDING'),
		('processing', 'PROCESSING'),
		('complete', 'COMPLETED'),
		('active', 'ACTIVE'),
		('inactive', 'INACTIVE'),
	)
	uuid = models.UUIDField(null=True, unique=True, default=uuid.uuid4, editable=False)
	status = models.CharField(max_length=100, choices=NOTIFICATION_STATUS_CHOICES)
	message = models.TextField()
	last_modified = models.DateTimeField(auto_now=True)
	notification = models.ForeignKey(Notification, on_delete=models.CASCADE)


class Source(models.Model):
	SOURCE_TYPE_CHOICES = (
		('video_file', 'VIDEO FILES'),
		('live', 'LIVE STREAM'),
	)
	SOURCE_STATUS_CHOICES = (
		('pending', 'PENDING'),
		('processing', 'PROCESSING'),
		('complete', 'COMPLETED'),
		('active', 'ACTIVE'),
		('inactive', 'INACTIVE'),
	)
	THRESHOLD_CHOICES = (
		(80, 80),
		(60, 60),
		(40, 40),
	)
	uuid = models.UUIDField(null=True, unique=True, default=uuid.uuid4, editable=False)
	source_type = models.CharField(max_length=100, choices=SOURCE_TYPE_CHOICES, blank=True, null=True)
	source_status = models.CharField(max_length=100, choices=SOURCE_STATUS_CHOICES, default='pending')
	source_name = models.CharField(max_length=500)
	video_file = models.FileField(upload_to=video_file_upload, blank=True, null=True)
	initial_timestamp = models.DateTimeField(default=datetime.now(), blank=True, null=True)
	camera_url = models.CharField(blank=True, null=True, max_length=500)
	threshold = models.IntegerField(choices=THRESHOLD_CHOICES, default=THRESHOLD_CHOICES[0])
	fps = models.IntegerField(default=5)
	user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)

	def __str__(self):
		return self.source_name


class AnalysisData(models.Model):
	uuid = models.UUIDField(null=True, unique=True, default=uuid.uuid4, editable=False, blank=True)
	timestamp = models.DateTimeField()
	source = models.ForeignKey(Source, on_delete=models.CASCADE)
	person = models.CharField(max_length=100)
	cropped_face = models.CharField(max_length=500, blank=True, null=True)

cloudview/recognition/forms.py
from django import forms
from .models import Person, PersonFace, Source

class PersonCreationForm(forms.ModelForm):
	class Meta:
		model = Person
		fields = ['first_name', 'middle_name', 'last_name', 'gender', 'email', 'phone_number', 'street', 'city', 'state', 'country', 'postal_code', 'description']


class PersonFaceCreationForm(forms.ModelForm):
	class Meta:
		model = PersonFace
		fields = ['image_name',]


class SourceForm(forms.ModelForm):
	class Meta:
		model = Source
		fields = ['source_name', 'video_file', 'initial_timestamp', 'camera_url', 'threshold', 'fps']

cloudview/recognition/views.py
from imutils import paths
import face_recognition
import pickle
import cv2
import os
from datetime import datetime
from cloudview.settings import BASE_DIR, MEDIA_URL

from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse

from .models import Person, PersonFace, Notification, NotificationHistory, Source
from .forms import PersonCreationForm, SourceForm, PersonFaceCreationForm
from catalog.models import Catalog

from .tasks import train_face as training
from .tasks import video_analysis, livestream_analysis

# Create your views here.
@login_required(redirect_field_name='login')
def person_list(request):
	user = request.user
	persons = Person.objects.filter(user=user).order_by('catalog')
	thumbnails = []
	for person in persons:
		face = PersonFace.objects.filter(person=person, train_status=True)
		try:
			thumbnails.append(face[0].crop_face_image)
		except:
			thumbnails.append('no_pic.jpg')
	personList = zip(persons, thumbnails)
	context = {'persons':personList}
	return render(request, 'recognition/person_list.html', context)


@login_required(redirect_field_name='login')
def add_person(request):
	user = request.user
	catalogs = Catalog.objects.filter(user_id=user)
	if (request.method == 'POST'):
		form = PersonCreationForm(request.POST)
		if form.is_valid():
			new_person = Person()
			new_person.user = user
			first_name = form.cleaned_data['first_name']
			middle_name = form.cleaned_data['middle_name']
			last_name = form.cleaned_data['last_name']
			if (first_name is not None):
				new_person.first_name = first_name.upper()
			if (middle_name is not None):
				new_person.middle_name = middle_name.upper()
			if (last_name is not None):
				new_person.last_name = last_name.upper()
			new_person.gender = form.cleaned_data['gender']
			new_person.email = form.cleaned_data['email']
			try:
				catalog_uuid = request.POST['catalog']
				new_person.catalog = Catalog.objects.get(uuid=catalog_uuid, user_id=user)
			except:
				pass
			new_person.save()
			# Creating notification type train for given person uuid
			notification = Notification()
			notification.notification_type = 'train'
			notification.related_uuid = new_person.uuid
			notification.user = user
			notification.save()
			# Creating notification history for the notification
			notification_msg = NotificationHistory(status='pending', notification=notification, message='[INFO] Successfully created person and added personal details.')
			notification_msg.save()
			return redirect('add_person_contact', new_person.uuid)
	else:
		form = PersonCreationForm()
	context = {'form':form, 'catalogs':catalogs}
	return render(request, 'recognition/add_person.html', context)

@login_required(redirect_field_name='login')
def add_person_contact(request, person_uuid):
	user = request.user
	if (request.method == 'POST'):
		form = PersonCreationForm(request.POST)
		if form.is_valid():
			new_person = Person.objects.get(uuid=person_uuid)
			new_person.phone_number = form.cleaned_data['phone_number']
			new_person.street = form.cleaned_data['street']
			new_person.city = form.cleaned_data['city']
			new_person.state = form.cleaned_data['state']
			new_person.country = form.cleaned_data['country']
			new_person.postal_code = form.cleaned_data['postal_code']
			new_person.description = form.cleaned_data['description']
			new_person.save()
			# Creating notification history
			notification = Notification.objects.get(related_uuid=person_uuid)
			notification_msg = NotificationHistory(status='pending', notification=notification, message='[INFO] Successfully added contact details.')
			notification_msg.save()
			return redirect('add_person_images', new_person.uuid)
	else:
		form = PersonCreationForm()
	context = {'form':form}
	return render(request, 'recognition/add_person_contact.html', context)

@login_required(redirect_field_name='login')
def add_person_images(request, person_uuid):
	user = request.user
	person = Person.objects.get(uuid=person_uuid)
	if (request.method == 'POST'):
		form = PersonFaceCreationForm(request.POST, request.FILES)
		if form.is_valid():
			new_image = PersonFace()
			new_image.person = person
			new_image.image_name = request.FILES['image_name']
			new_image.save()
			print (request.FILES['image_name'])
			# Creating notification history
			notification = Notification.objects.get(related_uuid=person_uuid)
			notification_msg = NotificationHistory(status='pending', notification=notification, message='[INFO] Successfully added image : {}.'.format(new_image.image_name))
			notification_msg.save()
			return HttpResponseRedirect(reverse('add_person_images', args=[person_uuid]))
		else:
			print (form.errors)
	else:
		form = PersonFaceCreationForm()
	context = {'form':form, 'person_uuid':person_uuid}
	return render(request, 'recognition/add_person_images.html', context)



@login_required(redirect_field_name='login')
def train_face(request, person_uuid):
	# Getting the related notification object
	try:
		notification = Notification.objects.get(notification_type='train', related_uuid=person_uuid)
	except:
		# Creating notification type train for given person uuid
		notification = Notification()
		notification.notification_type = 'train'
		notification.related_uuid = person_uuid
		notification.user = user
		notification.save()
	user = request.user
	person = Person.objects.get(uuid=person_uuid)
	training.delay(person_uuid)
	return redirect('person_list')


@login_required(redirect_field_name='login')
def delete_person(request, person_uuid):
	user = request.user
	person = Person.objects.get(uuid=person_uuid)
	if (person.user == user):
		person.delete()
	else:
		raise Http404("The person does not exist...")
	return redirect('person_list')



@login_required(redirect_field_name='login')
def analysis_index(request):
	context = {}
	return render(request, 'recognition/analysis_index.html', context)


@login_required(redirect_field_name='login')
def analysis_form(request, source_type):
	user = request.user
	if (source_type == 'live'):
		st = True
	elif (source_type == 'video_file'):
		st = False
	if (request.method == 'POST'):
		form = SourceForm(request.POST, request.FILES)
		if form.is_valid():
			new_source = Source()
			new_source.source_type = source_type
			new_source.source_name = form.cleaned_data['source_name']
			new_source.threshold = form.cleaned_data['threshold']
			new_source.fps = form.cleaned_data['fps']
			new_source.user = user
			if (source_type == 'video_file'):
				new_source.video_file = request.FILES['video_file']
				new_source.initial_timestamp = form.cleaned_data['initial_timestamp']
			elif (source_type == 'live'):
				new_source.camera_url = form.cleaned_data['camera_url']
				new_source.initial_timestamp = datetime.now()
			new_source.save()
			if (source_type == 'video_file'):
				notification = Notification()
				notification.notification_type = 'analysis'
				notification.related_uuid = new_source.uuid
				notification.user = user
				notification.save()
				video_analysis.delay(new_source.uuid)
			elif (source_type == 'live'):
				new_source.source_status = 'inactive'
				new_source.save()
				notification = Notification()
				notification.notification_type = 'source'
				notification.related_uuid = new_source.uuid
				notification.user = user
				notification.save()
				livestream_analysis(new_source.uuid)
			return redirect('manage_camera')
		else:
			print (form.errors)
	else:
		form = SourceForm()
	context = {'form':form, 'source_type':st}
	return render(request, 'recognition/analysis.html', context)


@login_required(redirect_field_name='login')
def manage_camera(request):
	user = request.user
	sources = Source.objects.filter(user=user, source_type='live')
	context = {'sources':sources}
	return render(request, 'recognition/manage_camera.html', context)


@login_required(redirect_field_name='login')
def manage_video(request):
	user = request.user
	videos = Source.objects.filter(user=user, source_type='video_file')
	context = {'videos':videos}
	return render(request, 'recognition/manage_video.html', context)


@login_required(redirect_field_name='login')
def toggle_camera_status(request, source_uuid):
	source = Source.objects.get(uuid=source_uuid)
	if (source.source_status == 'active'):
		source.source_status = 'inactive'
	else:
		source.source_status = 'active'
		livestream_analysis(source.uuid)
	source.save()
	return redirect('manage_camera')


@login_required(redirect_field_name='login')
def view_logs(request, notification_type, related_uuid):
	user = request.user
	notification = Notification.objects.get(user=user, notification_type=notification_type, related_uuid=related_uuid)
	logs = NotificationHistory.objects.filter(notification=notification).order_by('-pk')
	context = {'notification':notification, 'logs':logs}
	return render(request, 'recognition/logs.html', context)

cloudview/recognition/templates/recognition/add_person.html
{% extends 'cloudview/base.html' %}

{% load bootstrap3 %}

{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}

{% load static %}

{% block title %}
	Add Person Data
{% endblock %}

{% block extra_link %}
	<link rel="stylesheet" type="text/css" href="{% static 'user_authentication/css/registration.css' %}">
{% endblock %}

{% block sidebar %}	
	<div class="col-sm-3 col-md-2 sidebar">
		<ul class="nav nav-sidebar" id="sidebar-list">
			<li><a href="{% url 'dashboard' %}"> Dashboard</a></li>
			<li><a href="{% url 'report' %}"> Reports</a></li>
			<li><a href="{% url 'add_catalog' %}"> Manage Catalogs</a></li>
			<li class="active"><a href="{% url 'person_list' %}"> Manage Faces</a></li>
			<li><a href="{% url 'manage_camera' %}"> Manage Cameras</a></li>
			<li><a href="{% url 'manage_video' %}"> Manage Videos</a></li>
			<li><a href="{% url 'analysis_index' %}"> Analysis</a></li>
		</ul>
	</div>
{% endblock %}

{% block content %}
	<div class="col-md-8 col-md-offset-2">
		<div id="registration-form">
			<form action="" method="post" class="form">
				{% csrf_token %}
				<div class="row tab" id="account-detail">
					<div class="row registration-header">
						<p align="center" class="text-bold section-heading">
							Add New Person Data
						</p>	
					</div>
					<div class="row">
						<div class="col-md-12">
							<p class="label-bold">Catalog</p>
						</div>
					</div>
					<div class="row">
						<div class="col-md-12">
							<div class="form-group">
								<label class="sr-only control-label" for="id_catalog">Catalog</label>
								<select name="catalog" class="form-control" title id="id_catalog">
									{% for catalog in catalogs %}
										<option value="{{ catalog.uuid }}">{{ catalog.catalog_name }}</option>
									{% endfor %}
								</select>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-md-12">
							<p class="label-bold">Full Name</p>
						</div>
					</div>
					<div class="row">
						<div class="col-md-4">
							{% bootstrap_field form.first_name show_label=False %}
						</div>
						<div class="col-md-4">
							{% bootstrap_field form.middle_name show_label=False %}
						</div>
						<div class="col-md-4">
							{% bootstrap_field form.last_name show_label=False %}
						</div>
					</div>
					<div class="row">
						<div class="col-md-12">
							{% bootstrap_field form.email show_label=True %}
						</div>
					</div>
					<div class="row">
						<div class="col-md-12">
							{% bootstrap_field form.gender show_label=True %}
						</div>
					</div>
					<div class="row">
						{% buttons %}
							<div class="col-md-4 col-md-offset-4">
								<button type="submit" class="btn btn-primary btn-block">
									<div class="button">Next : Contact Details</div>
								</button>
							</div>
						{% endbuttons %}
					</div>
				</div>
			</form>
		</div>
	</div>
{% endblock %}

cloudview/recognition/templates/recognition/add_person_contact.html
{% extends 'cloudview/base.html' %}

{% load bootstrap3 %}

{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}

{% load static %}

{% block title %}
	Add Person Data
{% endblock %}

{% block extra_link %}
	<link rel="stylesheet" type="text/css" href="{% static 'user_authentication/css/registration.css' %}">
{% endblock %}


{% block sidebar %}	
	<div class="col-sm-3 col-md-2 sidebar">
		<ul class="nav nav-sidebar" id="sidebar-list">
			<li><a href="{% url 'dashboard' %}"> Dashboard</a></li>
			<li><a href="{% url 'report' %}"> Reports</a></li>
			<li><a href="{% url 'add_catalog' %}"> Manage Catalogs</a></li>
			<li class="active"><a href="{% url 'person_list' %}"> Manage Faces</a></li>
			<li><a href="{% url 'manage_camera' %}"> Manage Cameras</a></li>
			<li><a href="{% url 'manage_video' %}"> Manage Videos</a></li>
			<li><a href="{% url 'analysis_index' %}"> Analysis</a></li>
		</ul>
	</div>
{% endblock %}


{% block content %}
	<div class="col-md-8 col-md-offset-2">
		<div id="registration-form">
			<form action="" method="post" class="form">
				{% csrf_token %}
				<div class="row tab" id="account-detail">
					<div class="row registration-header">
						<p align="center" class="text-bold section-heading">
							Add New Person Data
						</p>	
					</div>
					<div class="row">
						<div class="col-md-12">
							{% bootstrap_field form.phone_number show_label=True %}
						</div>
					</div>
					<div class="row">
						<div class="col-md-12">
							<p class="label-bold">Address</p>
						</div>
					</div>
					<div class="row">
						<div class="col-md-4">
							{% bootstrap_field form.street show_label=False %}
						</div>
						<div class="col-md-4">
							{% bootstrap_field form.city show_label=False %}
						</div>
						<div class="col-md-4">
							{% bootstrap_field form.state show_label=False %}
						</div>
					</div>
					<div class="row">
						<div class="col-md-8">
							{% bootstrap_field form.country show_label=False %}
						</div>
						<div class="col-md-4">
							{% bootstrap_field form.postal_code show_label=False %}
						</div>
					</div>
					<div class="row">
						<div class="col-md-12">
							{% bootstrap_field form.description show_label=True %}
						</div>
					</div>
					<div class="row">
						{% buttons %}
							<div class="col-md-4 col-md-offset-4">
								<button type="submit" class="btn btn-primary btn-block">
									<div class="button">Next : Add Images</div>
								</button>
							</div>
						{% endbuttons %}
					</div>
				</div>
			</form>
		</div>
	</div>
{% endblock %}

cloudview/recognition/templates/recognition/add_person_images.html
{% extends 'cloudview/base.html' %}

{% load bootstrap3 %}

{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}

{% load static %}

{% block title %}
	Add Person Data
{% endblock %}

{% block extra_link %}
	<link rel="stylesheet" type="text/css" href="{% static 'user_authentication/css/registration.css' %}">
	<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/4.3.0/dropzone.css">
	<link rel="stylesheet" type="text/css" href="{% static 'recognition/css/dropzone.css' %}">
	<script type="text/javascript" src="{% static 'recognition/js/dropzone.js' %}"></script>
{% endblock %}


{% block sidebar %}	
	<div class="col-sm-3 col-md-2 sidebar">
		<ul class="nav nav-sidebar" id="sidebar-list">
			<li><a href="{% url 'dashboard' %}"> Dashboard</a></li>
			<li><a href="{% url 'report' %}"> Reports</a></li>
			<li><a href="{% url 'add_catalog' %}"> Manage Catalogs</a></li>
			<li class="active"><a href="{% url 'person_list' %}"> Manage Faces</a></li>
			<li><a href="{% url 'manage_camera' %}"> Manage Cameras</a></li>
			<li><a href="{% url 'manage_video' %}"> Manage Videos</a></li>
			<li><a href="{% url 'analysis_index' %}"> Analysis</a></li>
		</ul>
	</div>
{% endblock %}


{% block content %}
	<div class="col-md-8 col-md-offset-2">
		<div class="fileUpload">
			<form id="imageUploadDropzone" action="{% url 'add_person_images' person_uuid %}" method="post" class="dropzone needsclick" enctype="multipart/form-data">
				{% csrf_token %}
				<div class="dz-message needsclick">
					Drop Images Here or Click to Upload
					<br>
					<span class="note needsclick">
						(MAX Image Size - 5 MB)
					</span>
				</div>
			</form>
		</div>
		<div class="row">
			<a href="{% url 'train_face' person_uuid %}">
				<button class="btn btn-primary btn-block">
					Start Training
				</button>
			</a>
		</div>
	</div>
	<script type="text/javascript">
		Dropzone.options.imageUploadDropzone = {
			paramName: "image_name",
			maxFilesize: 5,
			acceptedFiles: "image/*",
			thumbnailHeight: 120,
			thumbnailWidth: 120,
		}
	</script>
{% endblock %}

cloudview/recognition/templates/recognition/analysis_index.html
{% extends 'cloudview/base.html' %}

{% load bootstrap3 %}

{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}

{% load static %}

{% block title %}
	Analyze Data - Select Source
{% endblock %}

{% block extra_link %}
	<link rel="stylesheet" type="text/css" href="{% static 'recognition/css/analysis.css' %}">
{% endblock %}

{% block sidebar %}	
	<div class="col-sm-3 col-md-2 sidebar">
		<ul class="nav nav-sidebar" id="sidebar-list">
			<li><a href="{% url 'dashboard' %}"> Dashboard</a></li>
			<li><a href="{% url 'report' %}"> Reports</a></li>
			<li><a href="{% url 'add_catalog' %}"> Manage Catalogs</a></li>
			<li><a href="{% url 'person_list' %}"> Manage Faces</a></li>
			<li><a href="{% url 'manage_camera' %}"> Manage Cameras</a></li>
			<li><a href="{% url 'manage_video' %}"> Manage Videos</a></li>
			<li class="active"><a href="{% url 'analysis_index' %}"> Analysis</a></li>
		</ul>
	</div>
{% endblock %}

{% block content %}
	<div class="col-md-10 col-md-offset-1">
		<div class="row">
			<div class="col-md-6 col-md-offset-3">
				<div class="heading">
					Select Source of Data to Analyze
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-4 col-md-offset-1">
				<a href="{% url 'analysis_form' 'video_file' %}">
					<div class="video-file">
						<div class="row">{% bootstrap_icon "film" %}</div>
						<div class="row">
							<p class="source-type">Video</p>
						</div>
					</div>
				</a>
			</div>
			<div class="col-md-2"></div>
			<div class="col-md-4">
				<a href="{% url 'analysis_form' 'live' %}">
					<div class="live-stream">
						<div class="row">{% bootstrap_icon "facetime-video" %}</div>
						<div class="row">
							<p class="source-type">Live Stream</p>
						</div>
					</div>
				</a>
			</div>
		</div>
	</div>
{% endblock %}